# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Releave' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Releave
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'

  target 'ReleaveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReleaveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
